export const TEXT = {
  한국어: {
    breadcrumb: "마이페이지 > 내 프로필 > 계정 설정",
    nickname: "닉네임",
    changeNickname: "닉네임 변경",
    enterNickname: "새 닉네임 입력 (최대 5글자)",
    nicknameUpdated: "닉네임이 변경되었습니다.",
    nicknameUpdateFail: "닉네임 변경에 실패했습니다.",
    nicknameRequired: "닉네임을 입력해주세요.",
    nicknameTooLong: "닉네임은 5글자 이하로 입력해주세요.",
    currentEmail: "현재 이메일",
    currentPassword: "현재 비밀번호",
    passwordUnavailable: "보안상 표시할 수 없습니다",
    close: "닫기",
    manage: "관리",
    save: "저장",
    security: "보안",
    securityDesc: "로그인 기록과 계정 보호 설정",
    check: "확인",
    profileChange: "프로필 변경",
    profileChangeDesc: "프로필 사진 변경 옵션 선택",
    change: "변경",
    choosePhoto: "사진에서 찾기",
    defaultImage: "기본이미지로 바꾸기",
    profileUpdated: "프로필 사진이 변경되었습니다.",
    profileUpdateFail: "프로필 사진 변경에 실패했습니다.",
    changePassword: "비밀번호 변경",
    newPassword: "새 비밀번호",
    confirmPassword: "새 비밀번호 확인",
    saveChange: "변경 저장",
    loginHistory: "로그인 기록",
    currentSession: "현재 접속",
    currentSessionDesc: "오늘 · 이 브라우저",
    recentLogin: "최근 로그인",
    noHistory: "기록 없음",
    display: "화면 & 사용 환경",
    displayDesc: "언어와 글자 크기 설정",
    settings: "설정",
    language: "언어 설정",
    fontSize: "글자 크기",
    small: "작게",
    normal: "보통",
    large: "크게",
    logout: "로그아웃",
    deleteAccount: "회원 탈퇴",
    logoutConfirm: "정말 로그아웃 하시겠습니까?",
    deleteConfirm: "정말로 탈퇴하시겠습니까?",
    deleteFail: "회원 탈퇴 처리에 실패했습니다.",
    passwordRequired: "현재 비밀번호와 새 비밀번호를 입력해주세요.",
    passwordMismatch: "새 비밀번호가 일치하지 않습니다.",
    passwordSaved: "비밀번호 변경 요청이 완료되었습니다.",
    passwordChangeFail: "비밀번호 변경에 실패했습니다.",
    displaySaved: "화면 설정이 저장되었습니다.",
  },
  English: {
    breadcrumb: "My Page > Profile > Account Settings",
    nickname: "Nickname",
    changeNickname: "Change Nickname",
    enterNickname: "Enter new nickname (Max 5 chars)",
    nicknameUpdated: "Nickname has been updated.",
    nicknameUpdateFail: "Failed to update nickname.",
    nicknameRequired: "Please enter a nickname.",
    nicknameTooLong: "Nickname must be 5 characters or less.",
    currentEmail: "Current Email",
    currentPassword: "Current Password",
    passwordUnavailable: "Cannot be shown for security",
    close: "Close",
    manage: "Manage",
    save: "Save",
    security: "Security",
    securityDesc: "Review login history and account protection",
    check: "Check",
    profileChange: "Edit Profile",
    profileChangeDesc: "Choose a profile photo option",
    change: "Change",
    choosePhoto: "Choose Photo",
    defaultImage: "Use Default Image",
    profileUpdated: "Profile photo has been updated.",
    profileUpdateFail: "Failed to update profile photo.",
    changePassword: "Change Password",
    newPassword: "New Password",
    confirmPassword: "Confirm New Password",
    saveChange: "Save Changes",
    loginHistory: "Login History",
    currentSession: "Current Session",
    currentSessionDesc: "Today · This browser",
    recentLogin: "Recent Login",
    noHistory: "No history",
    display: "Display & Preferences",
    displayDesc: "Language and font size settings",
    settings: "Settings",
    language: "Language",
    fontSize: "Font Size",
    small: "Small",
    normal: "Normal",
    large: "Large",
    logout: "Log Out",
    deleteAccount: "Delete Account",
    logoutConfirm: "Do you really want to log out?",
    deleteConfirm: "Do you really want to delete your account?",
    deleteFail: "Failed to delete account.",
    passwordRequired: "Please enter your current and new password.",
    passwordMismatch: "New passwords do not match.",
    passwordSaved: "Password change request completed.",
    passwordChangeFail: "Failed to change password.",
    displaySaved: "Display settings saved.",
  },
};
